### ISSUE TITLE
HK USP Match tactical [wpn_usp_tac] has wrong damage stats

### ISSUE THREAD

**Issue by Aurelite** [Grokitach/Stalker_GAMMA#117]
Its a 9mm pistol but has the damage stats of a .45
rpm also looks weird

        hit_impulse                 = 40
        hit_power                   = 0.55, 0.55, 0.55, 0.55
        hit_type                    = fire_wound
        fire_distance               = 300
        bullet_speed                = 260
        rpm                         = 640
        rpm_empty_click             = 250

https://github.com/Grokitach/Stalker_GAMMA/blob/main/G.A.M.M.A/modpack_addons/G.A.M.M.A.%20Weapon%20Pack/gamedata/configs/items/weapons/w_usp_tac.ltx

Also consider reducing the magazine capacity down from 22 to a sane 18.
The pistol would still be one of the best with the free picantinni rail. Now its completely OP and its dropped by every other merc.

**Comment by Grokitach** [comment]
Yup thanks, fixed in the dev branch :)
