### ISSUE TITLE
Loner SEVA bodysuit [scientific_outfit] has wrong br_class

### ISSUE THREAD

**Issue by Aurelite** [Grokitach/Stalker_GAMMA#118]
the Loner SEVA bodysuit has BR Class 8 like the SSP-99, while the other medium scientific suits have 36

```
;---- MEDIUM COMBAT SEVA (Like PS5) ----

![scientific_outfit]
hit_fraction_actor            = 0.9
br_class = 0.9

![bandit_scientific_dark_outfit]
hit_fraction_actor = 0.52
br_class = 0.52

![bandit_scientific_outfit]
hit_fraction_actor = 0.52
br_class = 0.52

![cs_scientific_outfit]
hit_fraction_actor = 0.52
br_class = 0.52

...
```
https://github.com/Grokitach/Stalker_GAMMA/blob/main/G.A.M.M.A/modpack_addons/G.A.M.M.A.%20Actor%20Damage%20Balancer/gamedata/configs/mod_system_items_armors_br_class_rework.ltx

**Comment by Grokitach** [comment]
Ah i need to check the armor to be sure. Thanks !

**Comment by Grokitach** [comment]
https://github.com/Grokitach/Stalker_GAMMA/commit/bcd3ce62bca97c078ad3f194a447a85f5b703343
