### ISSUE TITLE
Is There A Way To Get This Besides Discord?

### ISSUE THREAD

**Issue by Aversiac** [Grokitach/Stalker_GAMMA#164]
I would really love to try this pack, but I absolutely refuse to put my access to the entirety of the pack in the hands of Discord moderators. It looks cool, but the Discord is toxic af, with mods handing out mutes and permabans left and right. I also don't think I am alone in saying that having any software you are pushing exclusively available at the hands of unkempt moderators is a bit silly (:

**Comment by NonmaterialDouble** [comment]
+1
Discord is not a part of the Internet. No information published there can be found via search engines. The Internet Archive can't get stuff from Discord. You can't read Discord unless you have an account. And to get an account you have to complete CAPTCHA (which is often broken, but nobody bothers to fix it), and then tell the people who own Discord all kinds of private information about yourself (including your phone number, which in some countries is the same as handing someone your government-issued ID). Frankly, I consider this unacceptable. Please consider providing a way to get this without using Discord.

**Comment by Grokitach** [comment]
It's planned
