### ISSUE TITLE
Can someone with discord post the download link?

### ISSUE THREAD

**Issue by 6Fv** [Grokitach/Stalker_GAMMA#166]
For those of us that despise Discord and its lack of respect for privacy, would someone post the download link here?
It's embarrassing that you're asking people to boost your discord server just to download this.

**Comment by tim110011** [comment]
My suggestion as a player:
Need magnet download link, for...
  ( cross platform installer ) + yearly full version + monthly update pack + daily hotfix
Or put everything on github, create a release repo. git clone and play?
