### ISSUE TITLE
Potential issue with mod "185- Shader Driven Scopes - CrookR"

### ISSUE THREAD

**Issue by Noscka** [Grokitach/Stalker_GAMMA#173]
Mod "185- Shader Driven Scopes - CrookR" has custom dx10 and dx11 exe. Copying them into the mod folder, unsurprisingly, makes the game not even run. this could potentially mean that the mod won't work in game.

**Comment by Grokitach** [comment]
No the mod works, everything is taken care of with the GAMMA exe using uptodate patched engine thanks to MrDemonized
