### ISSUE TITLE
Change description of Experimental PSU "Reactor" to be consistent with changes introduced in 0.9.1.

### ISSUE THREAD

**Issue by LuxusDarkangel** [Grokitach/Stalker_GAMMA#195]
Commit 81a7539 introduced balance changes to PSUs, including the removal of regen. However, the description still mentions the regeneration effect:

> This model is an experimental prototype constructed based on schematics you obtained from Ecologists, using the latently static properties of the Battery artifact to generate endless amounts of power. The contained artifact feedback loop continuously generates small amounts of power, and passively charges the power supply of existing exoskeletons - while it is a near limitless power source, the additional power capacity has been removed in order to properly contain the artifact.

**Comment by Grokitach** [comment]
Thanks, fixed next patch
