### ISSUE TITLE
README includes no information on how to install the modpack

### ISSUE THREAD

**Issue by Michaellaneous** [Grokitach/Stalker_GAMMA#52]
Not sure how this happened, but instead of telling me how to install this modpack, the README points me to a discord server.  Why do I have to sign up for some 3rd party software that more than likely steals my data anyway to install your modpack?

**Comment by Grokitach** [comment]
Because you’ll have questions and there’s a dedicated team on answer them as well as bot commands to answer to your questions. 

Also, it’s much more likely people have a discord account than a GitHub account to manage issues.

**Comment by africalimedrop** [comment]
muh sekrit club. also, https://github.com/Grokitach/Stalker_GAMMA/raw/3822cd4166638158b6650688c5451e59af9e692d/G.A.M.M.A.%20Installer.exe

**Comment by 6Fv** [comment]
Super jank. I was excited to try out STALKER, but I'm not installing discord to download a mod.

**Comment by nPHYN1T3** [comment]
> Because you’ll have questions and there’s a dedicated team on answer them as well as bot commands to answer to your questions.
> 
> Also, it’s much more likely people have a discord account than a GitHub account to manage issues.

Questions best answered with static documentation rather than pray someone is around that will reply that knows how to fix the issue yada yada. There is zero logical sense for a chat room to replace documentation.
