### ISSUE TITLE
Using %c[color] tag with multibyte font causing unexpected line ending.

### ISSUE THREAD

**Issue by MrPinku** [Grokitach/Stalker_GAMMA#68]
This is a bug from original anomaly and will not appear with ENG/RUS.
I found the solution in this link ,  I hope it will be considered in the next update.
Big thanks about the GAMMA modpack! Hope I didn't bother you.
[https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/issues/6](url)

**Comment by Grokitach** [comment]
Thanks I will include this in the next batch of exes ;)
