### ISSUE TITLE
Grok's Modpack Installer

### ISSUE THREAD

**Issue by annon2077** [Grokitach/Stalker_GAMMA#75]
Is the `.Grok's Modpack Installer` open source? I can see its a .net assembly but its been obfuscated using SmartAssembly, why? Its just kinda sketchy that you ask to disable antivirus, enable powershell scripts and run it as admin. I'd like to look at the src to verify its not doing anything to my system that I am not authorizing. I can investigate further and decompile/reverse engineer, but I thought I'd ask for the src first and save me some time.

You can reach me on discord `Annon 2077#9308`

**Comment by Grokitach** [comment]
The source is not currently available and we are making a new installer anyways. Here’s a virus total analysis of the installer. 
https://www.virustotal.com/gui/file/c93a066e3d5dafe77468f4510ce29e464567e23f61f32fa10910032c73719554?nocache=1
