### ISSUE TITLE
Download outside of Discord

### ISSUE THREAD

**Issue by skobkin** [Grokitach/Stalker_GAMMA#83]
Is there any place where I can download this mod pack outside of Discord? It'd be very helpful.

I like S.T.A.L.K.E.R. series and want to play it, but I was banned in Discord (for using [Ripcord](https://cancel.fm/ripcord/)) and asked to delete my account. I despise them [enough](https://twitter.com/skobkin/status/1495892752982228992) to not to register there ever again.

It'd be good to have other registration-independent (and software vendor independent) source for download like magnet link to torrent or some public link.

**Comment by itzliru** [comment]
Use Mod Manager 2 and download the zip and put the mods in your custom mod folder dir. find a tutorial if you dont know how
https://www.youtube.com/watch?v=oMrUZ8ezIso

**Comment by Grokitach** [comment]
Currently no, you need a discord account, sorry.

**Comment by pleszczy** [comment]
That's a disappointment.
