### ISSUE TITLE
Mauser 98k forester fatal bug/crash

### ISSUE THREAD

**Issue by carloverso** [Grokitach/Stalker_GAMMA#86]
Crash to desktop issue while trying to install / change parts on Mauser 98k forester, kited from clear sky kit (don't know if it worked before kit)

https://i.imgur.com/jobU4xj.png

https://youtu.be/MeTSnXqu5Bw (crash)
https://i.imgur.com/dS6s87w.png

No idea how to report a bug, its replicable so if i can give logs/dumps let me know

**Comment by Grokitach** [comment]
Are you running default GAMMA ? This was fixed awhile ago I think, I will look into it.
